### ISSUE TITLE
Can you update the provider please?

### ISSUE THREAD

**Issue by yakirp88** [mancuniancol/script.quasar.extratorrent-mc#1]
I mean like the others providers so it can display the provider name on first row
Thanks

**Comment by mancuniancol** [comment]
I am in the process to do it. But, I am being too busy. Eventually, I will update this provider. First, I need to finish to translate all the providers from Pulsar to Quasar.

**Comment by mancuniancol** [comment]
Well, it will take a little longer.  I need to rewrite the providers to the new configuration. But, I will try to put extratorrent in the top of my list
